services:
  unburdy-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
