services:
  unburdy-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    env_file:
      - .env
    environment:
      - NUXT_API_BASE_URL=https://api.unburdy.de/api/v1      
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
