version: '3.8'

services:
  unburdy-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
